
### GET /
GET http://localhost:5003

### Register a user: POST /auth/register
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}

### Login a user: POST /auth/login
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
} 

### Fetch all todos,  GET /todos endpoint (protected)
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYzNzA4Mjg0LCJleHAiOjE3NjM3OTQ2ODR9.E3MlAK8UKbL4W-g47TOvtarjpGK54N88C7uqsKZ0VXI

### Creates a todo, POST /todos
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYzNzA4Mjg0LCJleHAiOjE3NjM3OTQ2ODR9.E3MlAK8UKbL4W-g47TOvtarjpGK54N88C7uqsKZ0VXI
Content-Type: application/json

{
    "task": "Learn Express.js"
}

### Update a todo, PUT /todos/:id (Protected)
PUT http://localhost:5003/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYzNzA4Mjg0LCJleHAiOjE3NjM3OTQ2ODR9.E3MlAK8UKbL4W-g47TOvtarjpGK54N88C7uqsKZ0VXI
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo, DELETE /todos/:id (protected)
DELETE http://localhost:5003/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYzNzA4Mjg0LCJleHAiOjE3NjM3OTQ2ODR9.E3MlAK8UKbL4W-g47TOvtarjpGK54N88C7uqsKZ0VXI
